// CodeGear C++Builder
// Copyright (c) 1995, 2014 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'DUnitX.IoC.pas' rev: 28.00 (Windows)

#ifndef Dunitx_IocHPP
#define Dunitx_IocHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// Pascal unit
#include <SysInit.hpp>	// Pascal unit
#include <System.Generics.Collections.hpp>	// Pascal unit
#include <System.TypInfo.hpp>	// Pascal unit
#include <System.Rtti.hpp>	// Pascal unit
#include <System.SysUtils.hpp>	// Pascal unit
#include <System.Generics.Defaults.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Dunitx
{
namespace Ioc
{
//-- type declarations -------------------------------------------------------
template<typename TInterface> __interface TActivatorDelegate__1;
// template<typename TInterface> typedef System::DelphiInterface<TActivatorDelegate__1<TInterface> > _di_TActivatorDelegate__1;
// Template declaration generated by Delphi parameterized types is
// used only for accessing Delphi variables and fields.
// Don't instantiate with new type parameters in user code.
template<typename TInterface> __interface TActivatorDelegate__1  : public System::IInterface 
{
	
public:
	virtual TInterface __fastcall Invoke(void) = 0 ;
};

__interface TActivatorDelegate;
typedef System::DelphiInterface<TActivatorDelegate> _di_TActivatorDelegate;
__interface TActivatorDelegate  : public System::IInterface 
{
	
public:
	virtual System::_di_IInterface __fastcall Invoke(void) = 0 ;
};

class DELPHICLASS TDUnitXIoC;
#pragma pack(push,4)
class PASCALIMPLEMENTATION TDUnitXIoC : public System::TObject
{
	typedef System::TObject inherited;
	
private:
	class DELPHICLASS TIoCRegistration;
	class PASCALIMPLEMENTATION TIoCRegistration : public System::TObject
	{
		typedef System::TObject inherited;
		
public:
		_di_TActivatorDelegate ActivatorDelegate;
		System::_di_IInterface Instance;
		_di_TActivatorDelegate __fastcall CreateSingletonActivator(const _di_TActivatorDelegate delegate);
		void __fastcall Initialize(const _di_TActivatorDelegate delegate, bool singleton);
public:
		/* TObject.Create */ inline __fastcall TIoCRegistration(void) : System::TObject() { }
		/* TObject.Destroy */ inline __fastcall virtual ~TIoCRegistration(void) { }
		
	};
	
	
	
private:
	bool FRaiseIfNotFound;
	System::Generics::Collections::TDictionary__2<System::UnicodeString,TIoCRegistration*>* FContainerInfo;
	static TDUnitXIoC* FDefault;
	
protected:
	System::UnicodeString __fastcall GetInterfaceKey(const System::Typinfo::PTypeInfo typeInfo, const System::UnicodeString AName = System::UnicodeString());
	System::_di_IInterface __fastcall InternalResolve(const System::Typinfo::PTypeInfo typeInfo, const System::UnicodeString AName = System::UnicodeString());
	void __fastcall InternalRegisterType(const System::Typinfo::PTypeInfo typeInfo, const bool singleton, const _di_TActivatorDelegate delegate, const System::UnicodeString name = System::UnicodeString());
	
public:
	__fastcall TDUnitXIoC(void);
	__fastcall virtual ~TDUnitXIoC(void);
	
private:
	// __classmethod void __fastcall ClassDestroy@();
	
public:
	__classmethod TDUnitXIoC* __fastcall DefaultContainer();
	template<typename TInterface, typename TImplementation> void __fastcall RegisterType(const System::UnicodeString name = System::UnicodeString())/* overload */;
	template<typename TInterface, typename TImplementation> void __fastcall RegisterType(const bool singleton, const System::UnicodeString name = System::UnicodeString())/* overload */;
	template<typename TInterface> void __fastcall RegisterType(const System::DelphiInterface<TActivatorDelegate__1<TInterface> > delegate, const System::UnicodeString name = System::UnicodeString())/* overload */;
	template<typename TInterface> void __fastcall RegisterType(const bool singleton, const System::DelphiInterface<TActivatorDelegate__1<TInterface> > delegate, const System::UnicodeString name = System::UnicodeString())/* overload */;
	template<typename TInterface> void __fastcall RegisterSingleton(const TInterface instance, const System::UnicodeString name = System::UnicodeString());
	template<typename TInterface> TInterface __fastcall Resolve(const System::UnicodeString name = System::UnicodeString());
	template<typename T> bool __fastcall HasService(void);
	void __fastcall Clear(void);
	__property bool RaiseIfNotFound = {read=FRaiseIfNotFound, write=FRaiseIfNotFound, nodefault};
	
private:
	// __classmethod void __fastcall Create@();
};

#pragma pack(pop)

class DELPHICLASS EIoCException;
#pragma pack(push,4)
class PASCALIMPLEMENTATION EIoCException : public System::Sysutils::Exception
{
	typedef System::Sysutils::Exception inherited;
	
public:
	/* Exception.Create */ inline __fastcall EIoCException(const System::UnicodeString Msg) : System::Sysutils::Exception(Msg) { }
	/* Exception.CreateFmt */ inline __fastcall EIoCException(const System::UnicodeString Msg, System::TVarRec const *Args, const int Args_High) : System::Sysutils::Exception(Msg, Args, Args_High) { }
	/* Exception.CreateRes */ inline __fastcall EIoCException(NativeUInt Ident)/* overload */ : System::Sysutils::Exception(Ident) { }
	/* Exception.CreateRes */ inline __fastcall EIoCException(System::PResStringRec ResStringRec)/* overload */ : System::Sysutils::Exception(ResStringRec) { }
	/* Exception.CreateResFmt */ inline __fastcall EIoCException(NativeUInt Ident, System::TVarRec const *Args, const int Args_High)/* overload */ : System::Sysutils::Exception(Ident, Args, Args_High) { }
	/* Exception.CreateResFmt */ inline __fastcall EIoCException(System::PResStringRec ResStringRec, System::TVarRec const *Args, const int Args_High)/* overload */ : System::Sysutils::Exception(ResStringRec, Args, Args_High) { }
	/* Exception.CreateHelp */ inline __fastcall EIoCException(const System::UnicodeString Msg, int AHelpContext) : System::Sysutils::Exception(Msg, AHelpContext) { }
	/* Exception.CreateFmtHelp */ inline __fastcall EIoCException(const System::UnicodeString Msg, System::TVarRec const *Args, const int Args_High, int AHelpContext) : System::Sysutils::Exception(Msg, Args, Args_High, AHelpContext) { }
	/* Exception.CreateResHelp */ inline __fastcall EIoCException(NativeUInt Ident, int AHelpContext)/* overload */ : System::Sysutils::Exception(Ident, AHelpContext) { }
	/* Exception.CreateResHelp */ inline __fastcall EIoCException(System::PResStringRec ResStringRec, int AHelpContext)/* overload */ : System::Sysutils::Exception(ResStringRec, AHelpContext) { }
	/* Exception.CreateResFmtHelp */ inline __fastcall EIoCException(System::PResStringRec ResStringRec, System::TVarRec const *Args, const int Args_High, int AHelpContext)/* overload */ : System::Sysutils::Exception(ResStringRec, Args, Args_High, AHelpContext) { }
	/* Exception.CreateResFmtHelp */ inline __fastcall EIoCException(NativeUInt Ident, System::TVarRec const *Args, const int Args_High, int AHelpContext)/* overload */ : System::Sysutils::Exception(Ident, Args, Args_High, AHelpContext) { }
	/* Exception.Destroy */ inline __fastcall virtual ~EIoCException(void) { }
	
};

#pragma pack(pop)

class DELPHICLASS EIoCRegistrationException;
#pragma pack(push,4)
class PASCALIMPLEMENTATION EIoCRegistrationException : public EIoCException
{
	typedef EIoCException inherited;
	
public:
	/* Exception.Create */ inline __fastcall EIoCRegistrationException(const System::UnicodeString Msg) : EIoCException(Msg) { }
	/* Exception.CreateFmt */ inline __fastcall EIoCRegistrationException(const System::UnicodeString Msg, System::TVarRec const *Args, const int Args_High) : EIoCException(Msg, Args, Args_High) { }
	/* Exception.CreateRes */ inline __fastcall EIoCRegistrationException(NativeUInt Ident)/* overload */ : EIoCException(Ident) { }
	/* Exception.CreateRes */ inline __fastcall EIoCRegistrationException(System::PResStringRec ResStringRec)/* overload */ : EIoCException(ResStringRec) { }
	/* Exception.CreateResFmt */ inline __fastcall EIoCRegistrationException(NativeUInt Ident, System::TVarRec const *Args, const int Args_High)/* overload */ : EIoCException(Ident, Args, Args_High) { }
	/* Exception.CreateResFmt */ inline __fastcall EIoCRegistrationException(System::PResStringRec ResStringRec, System::TVarRec const *Args, const int Args_High)/* overload */ : EIoCException(ResStringRec, Args, Args_High) { }
	/* Exception.CreateHelp */ inline __fastcall EIoCRegistrationException(const System::UnicodeString Msg, int AHelpContext) : EIoCException(Msg, AHelpContext) { }
	/* Exception.CreateFmtHelp */ inline __fastcall EIoCRegistrationException(const System::UnicodeString Msg, System::TVarRec const *Args, const int Args_High, int AHelpContext) : EIoCException(Msg, Args, Args_High, AHelpContext) { }
	/* Exception.CreateResHelp */ inline __fastcall EIoCRegistrationException(NativeUInt Ident, int AHelpContext)/* overload */ : EIoCException(Ident, AHelpContext) { }
	/* Exception.CreateResHelp */ inline __fastcall EIoCRegistrationException(System::PResStringRec ResStringRec, int AHelpContext)/* overload */ : EIoCException(ResStringRec, AHelpContext) { }
	/* Exception.CreateResFmtHelp */ inline __fastcall EIoCRegistrationException(System::PResStringRec ResStringRec, System::TVarRec const *Args, const int Args_High, int AHelpContext)/* overload */ : EIoCException(ResStringRec, Args, Args_High, AHelpContext) { }
	/* Exception.CreateResFmtHelp */ inline __fastcall EIoCRegistrationException(NativeUInt Ident, System::TVarRec const *Args, const int Args_High, int AHelpContext)/* overload */ : EIoCException(Ident, Args, Args_High, AHelpContext) { }
	/* Exception.Destroy */ inline __fastcall virtual ~EIoCRegistrationException(void) { }
	
};

#pragma pack(pop)

class DELPHICLASS EIoCResolutionException;
#pragma pack(push,4)
class PASCALIMPLEMENTATION EIoCResolutionException : public EIoCException
{
	typedef EIoCException inherited;
	
public:
	/* Exception.Create */ inline __fastcall EIoCResolutionException(const System::UnicodeString Msg) : EIoCException(Msg) { }
	/* Exception.CreateFmt */ inline __fastcall EIoCResolutionException(const System::UnicodeString Msg, System::TVarRec const *Args, const int Args_High) : EIoCException(Msg, Args, Args_High) { }
	/* Exception.CreateRes */ inline __fastcall EIoCResolutionException(NativeUInt Ident)/* overload */ : EIoCException(Ident) { }
	/* Exception.CreateRes */ inline __fastcall EIoCResolutionException(System::PResStringRec ResStringRec)/* overload */ : EIoCException(ResStringRec) { }
	/* Exception.CreateResFmt */ inline __fastcall EIoCResolutionException(NativeUInt Ident, System::TVarRec const *Args, const int Args_High)/* overload */ : EIoCException(Ident, Args, Args_High) { }
	/* Exception.CreateResFmt */ inline __fastcall EIoCResolutionException(System::PResStringRec ResStringRec, System::TVarRec const *Args, const int Args_High)/* overload */ : EIoCException(ResStringRec, Args, Args_High) { }
	/* Exception.CreateHelp */ inline __fastcall EIoCResolutionException(const System::UnicodeString Msg, int AHelpContext) : EIoCException(Msg, AHelpContext) { }
	/* Exception.CreateFmtHelp */ inline __fastcall EIoCResolutionException(const System::UnicodeString Msg, System::TVarRec const *Args, const int Args_High, int AHelpContext) : EIoCException(Msg, Args, Args_High, AHelpContext) { }
	/* Exception.CreateResHelp */ inline __fastcall EIoCResolutionException(NativeUInt Ident, int AHelpContext)/* overload */ : EIoCException(Ident, AHelpContext) { }
	/* Exception.CreateResHelp */ inline __fastcall EIoCResolutionException(System::PResStringRec ResStringRec, int AHelpContext)/* overload */ : EIoCException(ResStringRec, AHelpContext) { }
	/* Exception.CreateResFmtHelp */ inline __fastcall EIoCResolutionException(System::PResStringRec ResStringRec, System::TVarRec const *Args, const int Args_High, int AHelpContext)/* overload */ : EIoCException(ResStringRec, Args, Args_High, AHelpContext) { }
	/* Exception.CreateResFmtHelp */ inline __fastcall EIoCResolutionException(NativeUInt Ident, System::TVarRec const *Args, const int Args_High, int AHelpContext)/* overload */ : EIoCException(Ident, Args, Args_High, AHelpContext) { }
	/* Exception.Destroy */ inline __fastcall virtual ~EIoCResolutionException(void) { }
	
};

#pragma pack(pop)

class DELPHICLASS TClassActivator;
#pragma pack(push,4)
class PASCALIMPLEMENTATION TClassActivator : public System::TObject
{
	typedef System::TObject inherited;
	
private:
	static System::Rtti::TRttiContext FRttiCtx;
	
private:
	// __classmethod void __fastcall Create@();
	
public:
	__classmethod System::_di_IInterface __fastcall CreateInstance(const System::TClass AClass);
	__classmethod _di_TActivatorDelegate __fastcall CreateActivatorDelegate(const System::TClass AClass, System::Typinfo::PTypeInfo typeInfo, bool raiseOnError);
	
private:
	// __classmethod void __fastcall Destroy@();
public:
	/* TObject.Create */ inline __fastcall TClassActivator(void) : System::TObject() { }
	/* TObject.Destroy */ inline __fastcall virtual ~TClassActivator(void) { }
	
};

#pragma pack(pop)

//-- var, const, procedure ---------------------------------------------------
}	/* namespace Ioc */
}	/* namespace Dunitx */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_DUNITX_IOC)
using namespace Dunitx::Ioc;
#endif
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_DUNITX)
using namespace Dunitx;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Dunitx_IocHPP
